src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('new/', views.new_account, name='new'),
    path('edit/', views.edit_account, name='edit'),
    path('profile/', views.my_account, name='me'),
    path('profile/<pk>/', views.UserInfoView.as_view(), name='view'),
    path('profile/<pk>/blog/', views.UserBlogInfoView.as_view(), name='view_blog'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'),
]

src/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('post/new/', views.NewPostView.as_view(), name='post_new'),
    path('post/<pk>/edit/', views.EditPostView.as_view(), name='post_edit'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('', views.PostListView.as_view(), name='post_list'),
]

src/home/urls.py
from django.urls import path, re_path

from . import views
from accounts import views as account_views

app_name = 'home'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    path('<username>/', account_views.redirect_view, name='user_redirect'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from sites.models import Site
from time import time
post_dict = {
        'queryset': Post.objects.all(),
            'date_field': 'published_date'
}
sites_dict = {
    'queryset': Site.objects.all(),
}
sitemaps = {
        'blog': GenericSitemap(post_dict, priority=0.6),
        'home': GenericSitemap(sites_dict, priority=0.7),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('time/', include('clock.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('about/', include('about.urls')),
    path('fin/', include('birthday.urls')),
    path('mail/', include('mail.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
]

src/home/models.py
import datetime
import uuid
from django.db import models
from django.utils import timezone
from django.urls import reverse

class Details(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    welcome_msg = models.TextField(max_length=600)

    def __str__(self):
        return self.welcome_msg[:10]

src/home/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from blog.models import Post

from .models import Details

class CustomView():
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_more_context())
        context.update({
            'nav_links': [
                {'text': "Home", 'href': reverse('home:index')},
                {'text': "About", 'href': reverse('about:about')},
                {'text': "Contact", 'href': reverse('contact:contact')},
                {'text': "Links", 'href': reverse('about:links')},
                {'text': "Blog", 'href': reverse('blog:post_list')}
            ],
            'can_post': self.request.user.has_perm('blog.add_post')
            })

        return context

class IndexView(CustomView, generic.ListView):
    template_name = 'home/index.html'
    context_object_name = 'posts'

    def get_more_context(self):
        return {
            'title': 'Home',
            'welcome_msg': Details.objects.all().first().welcome_msg if Details.objects.all().first() else "Welcome to lukespademan.com",
            }

    def get_queryset(self):
        posts = [
            Post.objects.order_by('-published_date')[:2],
            Post.objects.order_by('-published_date')[2:4],
            Post.objects.order_by('-published_date')[4:6],
            ]
        return posts

src/home/templates/home/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
        <link href="{{STATIC_URL}}/favicon.ico" rel="shortcut icon" type="image/png">
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" rel="stylesheet">
        <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <script src="{% static 'turbolinks/turbolinks.js'%}"></script>
        <title>{% if title %}{{ title }} | lukespademan{% else %}lukespademan.com{% endif %}</title>
    </head>
	<body>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
					<a class="navbar-brand" href="{% url 'home:index' %}">lukespademan.com</a>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav mr-auto">
									{% for link in nav_links %}
									<li class="nav-item{% if link.href == request.path %} active {% endif %}">
											<a class="nav-link" href="{{ link.href }}">{{ link.text }}{% if link.href == request.path %}{% endif %}</a>
									</li>
									{% endfor %}
							</ul>
							<!--search bar-->

							<form action="/search/" class="form-inline my-2 my-lg-0" method="get">
									<input aria-label="Search" class="form-control mr-sm-2" name="q" placeholder="Search Blog" type="search"> <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
							</form>

							<ul class="navbar-nav justify-content-end">
									{% if can_post %}
									<div class="form-inline my-2 my-lg-0">
											<a class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'blog:post_new' %}" style="margin-left:4px;">New Post</a>
									</div>
									{% endif %} {% if request.user.username %}
									<li class="nav-item">
											<a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
									</li>
									{% else %}
									<li class="nav-item">
											<a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
									</li>
									{% endif %} {% if request.user.is_staff == True %}
									<li class="nav-item">
											<a class="nav-link" href="/admin/">Admin</a>
									</li>
									{% endif %}
							</ul>
					</div>
			</nav>

			<br>

			<div class="container-fluid" style="margin-bottom: 8px;">
					{% block content %} {% endblock %}
					<script crossorigin="anonymous" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
					<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
					<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
					<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
			</div>
	</body>
</html>

src/home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
    <title>
    </title>
</head>
<body>
    {% extends 'home/base.html' %} {% load markdownify %} {% load bleach_tags %} {% block content %}
    <h1>Welcome</h1>

    <p>{{ welcome_msg | markdown | safe | bleach }}</p>
    {% if posts %}
    <h1>Recent Posts</h1>

    <div class="container-fluid">
        <div class="row">
            {% for row in posts %} {% if row %} {% for post in row %}
            <div class="{% if row|length == 2 %}col-sm-6{% else %}col-sm-12{% endif %}" style="margin-bottom: 8px;">
                {% if row|length == 1 %} {% with long=1 %} {% include 'blog/post_preview.html' %} {% endwith %} {% else %} {% include 'blog/post_preview.html' %} {% endif %}
            </div>
            {% endfor %} {% endif %} {% endfor %}
        </div>
    </div>
    {% endif %} {% endblock %}
</body>
</html>