src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('new/', views.new_account, name='new'),
    path('edit/', views.edit_account, name='edit'),
    path('profile/', views.my_account, name='me'),
    path('profile/<pk>/', views.UserInfoView.as_view(), name='view'),
    path('profile/<pk>/blog/', views.UserBlogInfoView.as_view(), name='view_blog'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'),
]

src/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('post/new/', views.NewPostView.as_view(), name='post_new'),
    path('post/<pk>/edit/', views.EditPostView.as_view(), name='post_edit'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('', views.PostListView.as_view(), name='post_list'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from sites.models import Site
from time import time
post_dict = {
        'queryset': Post.objects.all(),
            'date_field': 'published_date'
}
sites_dict = {
    'queryset': Site.objects.all(),
}
sitemaps = {
        'blog': GenericSitemap(post_dict, priority=0.6),
        'home': GenericSitemap(sites_dict, priority=0.7),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('time/', include('clock.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('about/', include('about.urls')),
    path('fin/', include('birthday.urls')),
    path('mail/', include('mail.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
]

src/blog/models.py
import uuid
import datetime
from django.db import models
from django.utils import timezone
from django.urls import reverse
from mysite import settings

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=50000)
    created_date = models.DateTimeField('date created', default=timezone.now)
    published_date = models.DateTimeField('date published', blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def publish(self):
        self.published_data = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

src/blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-control'
                }),
            'title': forms.TextInput(attrs={
                'class': 'form-control'
                })
            }

src/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from home.views import CustomView
from .models import Post
from .forms import PostForm
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

class PostListView(CustomView, generic.ListView):
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

    def get_more_context(self):
        return {'title': "blog"}

    def get_queryset(self):
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        return posts

class PostDetailView(CustomView, generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    def get_more_context(self):
        return {'title': "blog"}

class NewPostView(LoginRequiredMixin, CustomView, generic.edit.FormView):
    template_name = 'blog/post_edit.html'
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        if super().form_valid(form):
            post = form.save(commit=False)
            post.author = self.request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)

    def get_more_context(self):
        return {'title': "blog"}

class EditPostView(LoginRequiredMixin, CustomView, generic.edit.UpdateView):
    template_name = 'blog/post_edit.html'
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def get_more_context(self):
        return {'title': "blog"}

    def form_valid(self, form):
        if super().form_valid(form):
            post = form.save(commit=False)
            post.author = self.request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)

src/blog/templates/blog/post.html
{% load gravatar %}
{% load markdownify %}
{% load bleach_tags %}
<div class="card">
    <div class="card-header">
        <a href="{% url 'accounts:view' pk=post.author.pk %}">
        <img src="{% gravatar_url post.author.email 30 %}" class="rounded-circle" /> {{ post.author }}</a>
    </div>
    <div class="card-body">
        <h{% if large %}1{% else %}5{% endif %} class="card-tilte"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h{% if large %}1{% else %}5{% endif %}>
        <h{% if large %}2{% else %}6{% endif %} class="card-subtitle mb-2 text-muted">{{ post.published_date }}</h{% if large %}2{% else %}6{% endif %}>
        <p class="card-text">{{ post.body | markdown | safe | bleach }}</p>
        {% if request.user.is_authenticated %} {% if request.user.pk == post.author.pk %}
        <div class="text-right">
            <a href="{% url 'blog:post_edit' pk=post.pk %}" class="card-link">edit</a>
        </div>
        {% endif %}{% endif %}
    </div>
</div>

src/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>
    </title>
</head>
<body>
    {% extends 'home/base.html' %} {% load gravatar %} {% block content %} {% with large=True %}{% include 'blog/post.html' %}{% endwith %} {% endblock %}
</body>
</html>

src/blog/templates/blog/post_edit.html
<!DOCTYPE html>
<html>
<head>
    <title>
    </title>
</head>
<body>
    {% extends 'home/base.html' %} {% block content %}
    <h1>New post</h1>

    <form class="post-form" method="post">
        {% csrf_token %} {{ form.as_p }} <button class="btn btn-primary" type="submit">Save</button>
    </form>
    {% endblock %}
</body>
</html>

src/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html>
<head>
    <title>
    </title>
</head>
<body>
    {% extends 'home/base.html' %} {% block content %} {% for post in posts %}
    <br>
    {% include 'blog/post.html' %} {% endfor %} {% endblock %}
</body>
</html>

src/blog/templates/blog/post_preview.html
{% load gravatar %}
{% load markdownify %}
{% load bleach_tags %}
<div class="card" style="margin-top 8px;">
    <div class="card-header">
        <a href="{% url 'accounts:view' pk=post.author.pk %}">
        <img src="{% gravatar_url post.author.email 30 %}" class="rounded-circle" /> {{ post.author }}</a>
    </div>
    <div class="card-body">
        <h{% if large %}1{% else %}5{% endif %} class="card-tilte"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h{% if large %}1{% else %}5{% endif %}>
        <h{% if large %}2{% else %}6{% endif %} class="card-subtitle mb-2 text-muted">{{ post.published_date }}</h{% if large %}2{% else %}6{% endif %}>
        <p class="card-text">{% if long %}{{ post.body |truncatechars:200 | markdown | safe | bleach }}{% else %}{{ post.body |truncatechars:100 | markdown | safe | bleach }}{% endif %}</p>
        <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">View</a>
    </div>
</div>